# Site settings
title: Draexx's Pages
description: a place for investigation and review.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Draexx
user_description: Freelance Author, Designer & Developer. Researcher Web & Desktop Technologies.
user_title: Software Developer
email: p.carranza.is@gmail.com
twitter_username: https://twitter.com/draexx
github_username:  https://github.com/draexx
codepen_username:  https://codepen.io/draexx
linkedin_username:  https://www.linkedin.com/in/pedrocarranza
dev_username:  https://dev.to/draexx

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
